package com.cyanrock.oms.common.em;

/**
 * 接口响应状态码
 *
 * @author 符冬
 */
public enum ResCodeEnum {
    SUCCESS(200, "成功"), INVALID_CLIENT(400, "请求有误"), INTERNAL_ERROR(500, "服务异常"), TOKEN_INVALIDATE(401, "无效的令牌"),
    REQUEST_OVERFREQUENCY(419, "正在处理中，请稍后."),
    TOKEN_REQUIRE(444, "令牌必传"), INSUFFICIENT_PRIVILEGE(405, "无权访问"), PARAM_EMPTY_ERROR(601, "参数为空"),
    PARAM_VALID_ERROR(602, "参数格式不正确"), PAGE_NOT_FOUND(404, "requested page is not available"), TRUE(1, "是"),
    FALSE(0, "否"),
    DATA_VERIFICATION(501, "数据校验失败"),

    // 通用
    NOT_FOUND(100001, "查无此记录"), ILLEGAL_STATUS(100002, "状态异常"), CUSTOMER_PERMISSION_IS_EMPTY(100003, "客户包权限为空"),
    NO_OPERATION_PERMISSION(100004, "无此操作权限"), USER_NOT_LOGIN(100005, "用户未登陆"), ILLEGAL_SID(100006, "非法sid"),
    NOT_CUSTOMER_INFO(100007, "客户包信息不存在"), SKU_ITEMSPEC_NOT_EXIST(100008, "SKU规格不存在"),
    CALL_FREIGHT_INTERFACE_ERROR(100009, "调用运费接口异常"), CRM_ERROR(100010, "CRM接口响应失败，请稍后再试或联系处理"),
    SAP_FREE_SHIPPING_ERROR(100011, "获取当前客户SAP免运费信息失败，请稍后再试或联系处理"), DATA_ERROR(100013, "数据异常"),
    // 报价业务状态码
    ONLY_QUOTATIONS_THE_SAME(300001, "仅可对同一客户的报价单合并转订单"), QUOTATION_TIME_LESS_CURRENT_TIME(300002, "报价时间小于当前时间"),
    SELECT_QUOTATION(300003, "请选择报价单"), SELECT_QUOTATION_LINE(300004, "请选择报价单行"),
    QUOTATION_TYPE_ERROR(300093, "报价单类型不一致！"),
    QUOTATION_TIME_IS_NULL(300005, "报价有效期不能为空"), QUOTATION_SAME_CUSTOMER(300006, "仅可针对同一客户"),
    QUOTATION_SKU_TYPE_NULL(300007, "报价行sku类型必填, 或不在范围"), QUOTE_QTY_GT_TRANSFER_QTY(300008, "报价数量不能大于可转数量"),
    QUOTATION_ADJUST_FREIGHT_EXISTS(300009, "已调整过运费的报价单，不可合并报价"),
    QUOTATION_ADJUST_FREIGHT_EXISTS_ORDER(300009, "已调整过运费的报价单，不可合并转订单"), QUOTATION_LINE_SKU_NULL(300010, "报价行SKU找不到"),
    QUOTATION_STATUS_DRAFT_OR_PARTFINISHED(300011, "报价单状态必须为可转订单或部分已清"),
    QUOTATION_LINE_STATUS_PARTFINISHED_OR_ALLNOTFINISHED(300012, "报价单行状态必须为部分已清或全部未清"),
    FREIGHT_ADJUST_CHECK_QUOTATION_STATUS(300013, "当前报价单状态不支持发起运费调整"),
    FREIGHT_ADJUST_NOT_DROP_SHIP_FLAG(300015, "不是直发物料的行，不能进行运费进行调整"),
    ONLY_TYPE_THE_SAME(300019, "仅可对同一类型的报价单合并转订单"),
    // FREIGHT_SHARING_QUOTATION_ONLY_ONE(300015, "该报价单已分摊过运费，无法申请运费调整"),
    FREIGHT_ADJUST_QUOTATION_ONLY_ONE(300016, "该报价单已申请过运费调整或分摊过运费，无法再次申请"), QUOTATION_CREATE_SUCCESS(300100, "创建报价单成功"),
    QUOTATION_CREATE_FAIL(300101, "创建报价单失败"), QUOTATION_LINE_CREATE_FAIL(300102, "创建报价行失败"),
    QUOTATION_LINE_SKU_CREATE_FAIL(300103, "创建报价行sku失败"), FREIGHT_NOT_SHARE(300105, "不分摊或摊到指定行"),
    QUOTATION_LINE_ALL_DROP_SHIP(300106, "头运费只能分摊到非直发物料上"), QUOTATION_QTY_GT_ZERO(300107, "报价数量必须大于0"),
    ILLEGAL_CLOSE_QTY(300108, "已转数量不符合要求"), ONLY_WHOLE_ORDER(300109, "已调整过运费的报价单只可整单转订单"),
    CHANNEL_NO_OMS(300110, "仅OMS渠道的报价单可以申请延长有效期"), EXTEND_VALIDATE_ONLY_ONE(300111, "只能申请一次有效期延长"),
    EXTEND_VALIDATE_CHECK_STATUS(300113, "当前报价单状态不支持发起有效期延长"), APPLY_SECOND_INQUIRY_ONLY_ONE(300115, "二次询价只可发起一次"),
    CUSTOMER_CODE_OR_NAME_IS_NULL(300116, "客户号或者客户名称不能为空"),
    APPROVAL_DISCOUNT_ILLEGAL_STATUS(300118, "当前报价单状态不支持发起审批流程"),
    APPROVAL_DISCOUNT_ILLEGAL_QUOTATION_TYPE(300119, "Sourcing报价单不可申请助力审批"),
    APPROVAL_DISCOUNT_QUOTATION_ONLY_ONE(300120, "该报价单已申请过助力，无法再次申请"),
    APPROVAL_DISCOUNT_CSP_TYPE(300121, "CSP的行不可以申请助力审批"), APPROVAL_DISCOUNT_ONLY_ONE(300123, "只能申请一次助力审批"),
    INVOICE_TITLE_EMPTY(300151, "发票抬头不能为空"), INVOICE_VAT_COMPANYNAME_EMPTY(300153, "发票单位名称不能为空"),
    LISTPRICE_MUST_GT_ZERO(100054, "面价必须大于0"), QUOTATION_SALES_PRICE_GT_ZERO(300005, "成交价必填"),
    FREIGHT_PARAMS_EMPTY(300155, "调用运费接口, 请求参数不能为空"), CHANNEL_NOT_OMS_REFUSE(300156, "非OMS、官企渠道的报价单, 不支持此操作"),
    QUOTATION_QTY_ILLEGAL(300158, "报价行的数量数据异常"), QUOTATION_LINE_QTY_ILLEGAL(300159, "报价行的数量, 不符合最小起订量要求"),
    SKU_MOQINCREMENT_ILLEGAL(300160, "最小起订量增幅不能为空，或者0, 请先联系商品产品经理更新数据"),
    PURCHPRICE_EMPTY(300161, "成本价必要信息缺失, 请先联系商品产品经理更新数据"), APPROVAL_DISCOUNT_CALLBACK(300163, "oa建议成交价回调接口失败"),
    APPROVAL_DISCOUNT_IMPORT_ERROR(300166, "助力审批导入失败"), COMBINE_QUOTATION_NOT_ONE(300167, "合并报价单至少2条报价单"),
    SKUTYPE_EMPTY(300161, "skuType必要信息缺失, 请先联系商品产品经理更新数据"),
    PURCHASEPRICE_EMPTY(300163, "costPrice必要信息缺失, 请先联系商品产品经理更新数据"),
    SALESNO_EMPTY(300165, "主销售号必要信息缺失, 请先联系CRM产品经理更新数据"), LEAST_ONE_QUOTATION(300166, "请至少选择一个报价单"),
    SYNC_PMS_QUOTATION_STATUS_ILLEGAL(300167, "可转订单、部分已清支持上架客，请重新选择"),
    SYNC_PRICE_QUOTATION_STATUS_ILLEGAL(300168, "可转订单、部分已清支持推送价格，请重新选择"),
    GET_FREIGHT_FREE_EXCEPTION(300169, "获取CRM是否免运费异常"), ALLOW_SOURCING_QUOTATION(300170, "仅Sourcing报价单进行内网上下架"),
    SALSES_NO_NOT_EMPTY(300170, "报价单主销售不能为空"), SELECT_FA_SKU_NOT_PUBLIC(300171, "仅可对未上架的FA操作"),
    SELECT_FA_SKU_PUBLIC(300172, "仅可对已上架的FA操作"), CHANNEL_NOT_OMS(300173, "渠道不能为OMS"),
    GPS_LOCK_RELEASE_ERROR(300175, "调用gps报价单锁定及解锁接口请求失败"), GPA_SOURCINGQUOTCREATE_ERROR(300177, "调用gps下报价单接口请求失败"),
    SKU_DATA_ERROR(300178, "报价行sku数据异常"),
    SAVE_OA_WORKFLOW_LINE_ERROR(300179, "保存OA备份报价报价行, 失败"),
    QUOTVALIDDATE_EMPTY(300180, "报价有效期必填"),
    OPERATION_PERMISSION(300176, "操作权限配置重复"),
    SKU_FA_NOT_SUPPORT_APPROVALDISCOUNT(300181, "含FA物料，不可发起助力审批"),
    DISCOUNTCODE_YPR0_NOT_SUPPORT_APPROVALDISCOUNT(300182, "折扣类型为YPR0，不可发起助力审批"),
    APPROVAL_IMPORT_LINE_ID_ERROR(300183, "助力审批导出数据有误, 行id不一致"),
    APPROVAL_IMPORT_SKU_ERROR(300185, "助力审批导出数据有误, sku不一致"),
    CONTACTCODER3_NOT_EMPTY(300186, "R3联系人代号为空"),
    QUOT_WEBSITESAVE_ERROR(300187, "成交价！=面价 明细折扣必须要传"),
    QUOT_WEBSITESAVE_DISCOUNT_ERROR(300188, "折扣明细只能为YPR0 YD29 YD19 YD35 YD17之一"),
    EC_LOCK_RELEASE_ERROR(300189, "通知ec审批结果失败"),
    INVOICE_TEL_MOBILE(300190, "发票手机号和固话不能都为空"),
    CONSIGNEE_TEL_MOBILE(300191, "收货人手机号和固话不能都为空"),
    QUOT_SALESPRICE_LOSE(300192, "成交价不能为负"),
    QUOT_CREATE_DISCOUNT_CHECK(300193, "折扣金额 折扣率 附加小计不可全部为空"),
    QUOT_CREATE_DISCOUNT_ALLSALES_CONSISTENT(300194, "当前无有效申请折扣行，请重新填写"),

    QUOT_APPROVALDISCOUNT_DISCOUNT_YD17_ERROR(300195, "折扣明细包含YD17类型的行，不支持申请助力"),

    QUOT_APPROVALDISCOUNT_DISCOUNT_YD25_ERROR(300196, "不允许编辑申请成交价"),
    QUOT_LINE_QTY_SALE_ERROR(300197, "报价数量不满足销售要求"),
    QUOT_WEBSITESAVE_CITY_ERROR(300198, "企业站渠道报价单,省市必须要传"),
    QUOT_WEBSITESAVE_NAME_ERROR(300199, "企业站渠道报价单,收货人名称与收货人地址必须要传"),


    DATA_EMPTY_ERROR(602, "数据不存在"), DATA_UPDATE_ERROR(603, "数据修改失败"), NOT_TYPE_ERROR(604, "类型不存在"),
    NOT_TYPE_DATA_ERROR(605, "此类型对应的数据不存在"), STATUS_TYPE_ERROR(606, "此订单状态异常,不能进行此操作"),
    RECEIVER_UPDATE_ERROR(607, "收货信息修改失败"), INVOICE_UPDATE_ERROR(608, "开票信息修改失败"), ORDER_UPDATE_ERROR(609, "订单信息修改失败"),
    CSR_APPROVE_ERROR(610, "非CSR主数据审核状态"), ORDER_NOT_CUSTOMER_INFO(611, "客户包信息不存在"),
    ORDER_NOT_CONTACT_INFO(612, "联系人信息不存在"), ORDER_PARAM_VALID_SHIPZIP(613, "订单收货邮编格式有误，需填写6位数据！"),
    ORDER_NOT_CHANNEL(614, "渠道号不存在"), ORDER_PARAM_VALID_CHANNEL(615, "渠道号已失效"), ORDER_PARAM_NOT_LINES(616, "订单行明细不能为空"),
    NOT_ORDER_LINES_ERROR(617, "订单行信息不存在"), NOT_ORDER_ERROR(618, "订单信息不存在"), ORDER_LINES_UPDATE_ERROR(619, "订单行信息修改失败"),
    ORDER_LINE_SPECIAL_REQ_ERROR(620, "此订单行已申请过此操作,请勿重复申请"), NOT_REF_FILE_ERROR(621, "附件信息不能为空"),
    ORDER_EXISTED_ERROR(622, "订单已存在"), ORDER_TOTAL_ERROR(623, "调整单价不能低于1块钱!"),
    NOT_ORDER_DETAIL_PRODUCT_ERROR(624, "订单行产品信息不存在!"), CSR_APPROVE_ORDER_ERROR(625, "非CSR订单审核状态"),
    ORDER_STATUS_ERROR(626, "订单状态不支持当前操作!"), ORDER_PRICE_UPDATE_ERROR(627, "单价调整仅可在1元以内"),
    NOT_SUB_TYPE_ERROR(628, "数据子类型不存在"), NOT_SOURCE_TYPE_ERROR(629, "数据类型不存在"),
    WARE_HOUSE_EXISTED_ERROR(630, "配置信息已存在"), CONFIRM_BOOKING_ORDER_ERROR(631, "当前订单不允许预订单确认!"),
    SPECIMAL_ORDER_ERROR(631, "当前订单不允许45编码确认!"),
    HTTP_STATUS_ERROR(632, "请勿重复提交!"), CHANNEL_EMPTY(633, "不存在渠道信息!"), CHANNEL_ENABLED(634, "该渠道已被禁用!"),
    CHANNEL_CONFIG_EXISTED_ERROR(635, "该渠道已存在配置信息!"), CHANNEL_EXISTED_ERROR(636, "该渠道号已存在!"),
    ORDER_PRODUCT_UPDATE_EXISTED_ERROR(637, "该订单已经提交过订单产品修改申请，请勿重复提交!"),
    ORDER_PRODUCT_REQUEST_AMOUNT_ERROR(638, "申请替换金额不能大于订单行总计金额!"), CUSTOMER_CONFIG_EMPTY(639, "该客户配置信息不存在!"),
    CUSTOMER_CONFIG_EXISTED_ERROR(640, "该客户已存在配置信息!"), ORDER_UPDATE_EXISTED_ERROR(641, "该订单已存在修改申请信息!"),
    ORDER_REQUEST_STATUS_ERROR(642, "申请状态只能为草稿中或者审批中!"), ORDER_REQUEST_CANCEL_ERROR(643, "申请类型为整单取消/部分取消，取消原因必选!"),
    ORDER_REQUEST_CANCEL_VALID(644, "取消原因不存在!"), ORDER_REQUEST_UPDATE_ERROR(645, "申请类型为订单修改，修改类型/修改原因必选!"),
    ORDER_REQUEST_UPDATE_VALID(646, "修改类型/修改原因不存在!"), ORDER_REQUEST_APPROVED_COMPLETED(647, "当前申请已审批完成，请勿重复调用!"),
    WARE_HOUSE_MAPPING_PARAM_ERROR(648, "不能把同仓库设置为该仓库平行仓!"), WARE_HOUSE_MAPPING_LEVEL_ERROR(649, "该仓库已存在添加的优先级平行仓!"),
    ORDER_ITEM_NOT_FOUND(650, "不存在物料信息!"), ORDER_SEND_TO_SAP_ERROR(651, "订单已同步!"), PRE_FLAG_ERR(652, "非预订单!!!"),
    EMPTY_ORDER_NO(653, "订单号为空!!!"),
    CUSTOMER_NOT_ERR(100050, "客户信息缺失,客户号:%s,请联系技术支持处理"),
    OAINITIATOR_NOT_NULL(100050, "该销售:%s 成本中心信息不存在,请联系技术支持处理"),

    SYNC_SAP(654, "该订单已同步SAP!!!"), ORDER_PRODUCT_REQUEST_QTY_ERROR(655, "申请替换数量不能大于订单行总数量!!!"),
    REMARK_EMPTY(656, "请至少填一种备注信息"), CANCEL_ERR(657, "该订单已取消!!!"), ORDER_PROCESSING(658, "订单处理中!!!"),
    RECEIVER_NOT_NULL(659, "收货区域信息缺失，请去CRM维护相关信息"), ORDER_PRICE_MAXTEN_ERROR(668, "整单价格不能超10元!!"),
    TOTAL_AMOUNT_ERR(660, "输入的小计含税不能为空!!"),
    SPECAIL_SKU_ERR(661, "客户特供产品,无法替换"),
    PRICE_REPLACE_ERR(662, "替换的价格信息不存在！！！"),
    QTY_REPLACE_ERR(663, "替换的数量为0！"),
    QUOTATION_LINE_NOT(664, "报价单行信息不存在"),
    QUOTATION_ES_STATUS_ERROR(6009, "客户内部审批状态，不支持当前操作!"),
    QUOTATION_STATUS_ERROR(6011, "报价单状态，不支持当前操作!"),
    QUOTATION_TYPE_NOT_ERROR(6010, "报价单类型不支持当前操作!"),
    QUOTATION_LINE_EXPIRED_ERROR(6022, "报价单行有效期存在已过期!"),
    QUOTATION_NOT(667, "报价单信息不存在！"),
    QUOTATION_CODE_EMPTY_ERROR(6650, "报价单号为空！"),

    QUOTATION_SYNC_API(668, "报价单状态变更通知失败！"),
    QUOTATION_CODE(6008, "报价单号重复，创建失败！"),
    QUOTATION_LINE_ERROR(6012, "无可转订单的报价单行，无法合并！"),
    SOURCE_TYPE_NOT_FOUND(665, "请求的单号类型不存在"),
    REPEAT_APPLICATION(402, "重复请求"),
    STATUS_ERROR(403, "状态不匹配"), FORBIDDEN(403, "无权限"), // 服务器理解请求客户端的请求，但是拒绝执行此请求

    APPLY_QTY(656, "申请数量不能大于发货数量"), OBDNO_NOT_FOUND(657, "发货单号不存在"), NOT_SEND(670, "发货单号在审批中，不能发起二次申请！"),
    INTERFACE_ERR_CODE(659, "接口异常"),
    SEND_KAFKA_ERROR(6444, "发送Kafka失败！"),
    WEBSITE_ERR_CODE(579, "官网-必囤好货接口异常"),
    ADDRESS_ERR(671, "地址信息有误，请重新选择收货地址"),
    DIFFERENT_ADDRESS_CODE(672, "地址信息与CRM不一致,是否更新?"),
    RECEIVER_MOBILE_ERR(673, "收货地址的手机和固话不能同时为空"),
    INVOICE_MOBILE_ERR(674, "发票寄送地址的手机和固话不能同时为空"),
    INVOICE_MOBILE_EMAIL_ERR(699, "发票寄送地址的手机和固话和邮箱不能同时为空"),
    MARGIN_ERR(675, "超出可输入范围!"),
    PRICE_CENTER_PRICE_ERR(676, "价格中心返回数据异常 sku: %s"),
    YD_STOCK_ERR(677, "查询库存信息失败！sku: "),
    OPERATION_ORDER_STATUS_ERR(678, "订单状态异常,请查看此订单是否已经被取消或者有流程在正在审批中!"),
    OPERATION_ORDER_STATUS_REPETITION(679, "该订单已经申请过取消操作了，请勿重复提交"),
    SAP_SYNC_PROCESSING(690, "该订单准备或者正在同步SAP,请稍后再试!"),
    ORDER_SYNC_API(680, "订单状态变更通知失败！"),
    REQUEST_TYPE_ERR(691, "请求类型异常，请确认后再操作!"),
    // 需求行明细 处理业务状态码
    INQ_LINE_TYPE_ERROR(200001, "根据填写的SKU号和品牌类型设置此行的行项目类型失败"), INQ_CANT_DEAL_MULTI(200002, "不可跨需求单操作"),
    INQ_NOT_ENOUGH_LINE(200003, "需求单清单条目不满足要求，不可提交"), INQ_NULL_SEGMENT(200004, "请先设置Product和Segment值"),
    INQ_NAME_NOT_NULL(200005, "需求产品名称必填。"), INQ_MUST_FILL_ONE(200006, "需求制造商型号和客户期望单价必需填一项，不能同时为空。"),
    INQ_UNIT_NOT_NULL(200008, "需求采购单位必填。"), INQ_NUM_NOT_NULL(200009, "需求数量必填。"),
    INQ_REPLACE_NOT_NULL(200010, "是否可替换必填。"), INQ_LONG_NUM_NOT_NULL(200011, "选择长期采购时对应长期采购数量必填。"),
    INQ_SELECT_NOT_NULL(200012, "请选择需求单"), INQ_SELECT_ONE_CUSTOMER_NULL(200013, "仅可选择同一客户的需求单进行报价"),
    INQ_BRAND_NAME_NULL(200014, "请输入品牌关键字后查询"), INQ_QUOTATION_TIME_OUT(200015, "已过报价有效期"),
    INQ_QUOTATION_SKU_STATUS_ERROR(200016, "存在SKU对应状态不支持此操作"), INQ_SKU_IS_EMPTY(200017, "SKU号必填。"),
    INQ_SKU_IS_NOT_FA(200018, "SKU: %s : 仅可输入FA类型的SKU，不能输入目录品类型的SKU。"), INQ_SKU_IS_NOT_EXIST(200019, "SKU不存在"),
    INQ_SKU_IS_NOT_CATALOGUE(200020, "仅可输入目录品类型的SKU。"), INQUIRY_CANCEL333(200021, "取消需求失败"),
    INQUIRY_CANCEL_ERROR_STATUS(200022, "部分需求单所属状态不支持取消操作，请确认后重新选择"), INQUIRY_CUSTOMER_DISCOUNT(200023, "客户对应折扣信息缺失"),
    INQUIRY_LINE_CANCEL_STATUS_ERROR(200024, "部分需求行状态不支持取消操作,请确认后重新选择!"),
    INQUIRY_LINE_IMPORT_NUM_ERROR(200025, "导入行数超过上限。限制条数为：%s"), INQUIRY_LINE_EDIT_ITEMS_EMPTY(200027, "需求单编辑清单明细不存在"),
    INQUIRY_LINE_DELETE_ITEMS_ERROR(200028, "需求单删除清单明细不存在"), INQUIRY_PARAM_NOT_LINES(200029, "需求单提交操作，清单明细不能为空"),
    INQUIRY_SKU_TYPE_MISMATCH(200030, "SKU: %s : SKU类型与需求类型不符。"),
    INQUIRY_SKU_IS_NOT_EXITS(200031, "SKU: %s : 不存在。"),
    INQUIRY_TO_QUOTE_AMOUNT_ERROR(200032, "需求单可转报价时需求总金额计算失败，请确认所有行成交价格信息是否完善"),
    INQ_SELECT_ONE_CHANNEL_ERROR(200033, "不可跨渠道转转报价"), INQ_SELECT_CANCEL_GPS_ERROR(200034, "GPS渠道的需求单不支持在OMS里取消"),
    INQ_GPS_CATEGORY_NULL_ERROR(200035, "GPS/GPS-Punchout 渠道的需求单清单明细必填 Product 和 Segment信息"),
    INQ_WARECODE_IS_EMPTY(200036, "仓库必填。"), INQUIRY_TO_QUOTE_CSP_ERROR(200037, "不支持招投标CSP的需求单合并转报价"),
    INQUIRY_API_ADD_SOURCE_ID_ERROR(200038, "新增API需求单，原单id缺失"), INQUIRY_API_ADD_REPEAT_ERROR(200039, "新增API需求单重复操作"),
    INQUIRY_API_ADD_API_INQ_TYPE_ERROR(200039, "API渠道只能选择API询价类型"),
    INQUIRY_INQ_TYPE_QUOTE_ERROR(200039, "API询价不可以在OMS转报价单"),
    INQUIRY_API_ADD_CSP_ERROR(200038, "新增API需求单，不可选中招投标CSP客户目的"),
    INQUIRY_IMPORT_ERROR(200039, "导入文件解析失败，请确认是否正确使用或修改过对应模板"),
    QUOT_UP_DOWN_SKU_ERROR(200040, "上架/下架操作失败"),
    QUOT_SKU_PURCHASE_ERROR(200041, "获取SKU号为：%s 的采购信息失败"),
    APPLY_DISCOUNT_OUT_ERROR(200042, "申请折扣率超出范围：%s"),
    INQUIRY_NEED_SOURCING_ERROR(200042, "仅能提交行项目状态为【需要Sourcing】的行项目"),
    INQUIRY_LNQID_IS_NOT_EXITS(200045, "需求行信息不存在。对应行id为：%s"),
    INQUIRY_LINE_CANCEL_SOURCING_ERROR(200043, "该SKU：%s 在原需求单中已取消，不可发起二次询价"),
    INQUIRY_SYNC_API(200045, "需求单状态变更通知失败！"),
    INQUIRY_OMS_ADD_API_INQ_TYPE_ERROR(200050, "OMS渠道只能选择普通询价类型"),
    INQ_UNIT_FORMAT_ERR(200051, "需求采购单位格式错误。"),
    INQ_PRICE_PARITY_ERR(200053, "客户目的为比价反拍的需求单不可以和其他客户目的需求单合并转报价单"),
    INQUIRY_TO_QUOTE_CONSIGNMENT_ERROR(200054, "不支持寄售的需求单合并转报价"),
    //借贷申请
    LOAN_APPLY_EXPIRE(200051, "【系统发票号】失效，请重新发起！"),
    NOT_QUOT_CODE_ERROR(204444, "报价单编号不能为空！"),

    // OA
    OA_ERROR(7001, "OA流程提交失败！"), OA_CALLBACK_ERROR(7002, "OA回调的流程Id不存在！"), OA_CALLBACK_STATUS_ERROR(7003, "OA回调的状态为空！"),
    OA_CALLBACK_STATUS_VALUE_ERROR(7004, "OA回调的状态错误！"), OA_WORKFLOW_ERR(7005, "流程信息不存在！"),

    AFTER_SALES_CANCEL(5001, "该售后申请已不支持取消！"),
    AFTER_SALES_EMPTY(5002, "售后申请不存在！"),
    COMMISSIONER_HANDLED(5010, "该操作仅限售后专员处理！"),
    SCRAP_PRICE_EMPTY(5003, "行明细-报废售价至少一行不能为0"),
    LINE_EMPTY(5004, "行明细为空！"),
    AFTER_SALES_OA_CODE(5005, "售后配置原因-oACode为空！"),
    AFTER_SALES_SYNC_API(5006, "售后申请同步API失败！"),
    SALES_ORDER_STOCK_NOT(5007, "%s的促销活动库存为%s，不满足下单数量，无法创建订单。"),
    HANDLED_BY(5008, "处理人不存在，无法创建任务！！"),
    SALES_EMPTY(5009, "OA回调主销售不存在,无法更新成本中心！"),
    ENT_COST_ERROR(5110, "企业站成本中心操作失败！"),
    APPLY_STATUS_ERROR(5011, "申请状态已更新，请刷新页面重新处理！"),
    SKU_STATUS_60(6000, "【%s】为询价商品不可其他商品生成报价单，请重新选择后生成报价单"),
    // jasper
    WRONG_FORMAT(604, "模板文件格式不对，请以.jasper为后缀的文件!"), READ_IMAGE_WRONG(604, "读取图片失败!"),
    WRITE_DATA_WRONG(602, "在进行数据填充时发生了错误中，请检查是否是数据库连接错误或者是用来填充的参数有误!"), DATA_EMPTY(602, "数据源为空!"),
    MASTERJV_EXISTED_ERROR(5004, "该JV Code已存在！"),
    READ_FIIL_ERROR(604, "读取文件失败!"),
    READ_EXCEL_FIIL_ERROR(604, "读取Excel文件失败!"),
    EXPORT_EXCEL_FIIL_ERROR(704, "读取Excel文件失败!"),
    ORDER_REQUEST_USERNAME_ERROR(200054, "该员工工号不存在！员工名为：%s"),
    ORDER_REQUEST_OA_ID_ERROR(200054, "该员工工号在OA系统不存在ID！工号名为：%s"),
    ORDER_REQUEST_SKU_NAME_ERROR(200054, "该SKU对应的员工不存在，请咨询有关部门！SKU号为：%s"),
    DEPT_NAME_ERROR(200054, "部门名称为空！"),
    ORDER_MODIFY_SYNC_SAP(6001, "订单修改同步sap失败！"),
    ORDER_CANCEL_SAP(6002, "系统取消订单失败！"),
    ORDER_SYNCING_SAP(6003, "订单业务处理中，请稍后尝试取消！"),
    BIZSTATUS_ERR(6004, "该sku%s业务状态异常"),
    API_BIZSTATUS_ERR(6007, "不允许创建含业务状态为60的sku"),
    FAMILY_ERR(200055, "Family必填;"),
    DATA_SKU_ERROR(200026, "sku数据异常 sku号：%s"),
    ASSORTMENT_SKU_ERROR(100027, "获取fa已转目录品sku数据异常"),
    QUOTE_NOT_APPROVALDISCOUNT_ERROR(100030, "该SKU不支持助力申请,sku号:%s"),
    SMALL_PACKAGE_SKU_ERROR(100030, "请选择最小包装单位sku号导入,异常sku号:%s"),
    NOT_SUPPORT_CREATE(100031, "%s暂不可售，无法生成报价单"),
    NOT_SUPPORT(100032, "以下sku业务状态不支持此项操作:%s"),
    ORDER_DISCOUNTAMOUNT_ERROR(6004, "行小计校验有误，请联系管理员。"),
    NOT_SUBMIT_DATA_ERR(100033, "无实时询价任务行需要提交"),
    CUSTOMER_NOT_NULL(100050, "客户信息必填!"),
    FIXED_PRODUCT_ERR(100055, "定制品选择“是”时，定制品图纸必须上传!"),
    REQUESTTYPE_NOT_NULL(100051, "申请类型不能为空!"),
    REMARK_NOT_EMPTY(100052, "备注信息不能为空"),
    DATA_NOT_EMPTY(100053, "数据缺失，请联系技术支持"),
    QUOTATION_LINE_NULL(100054, "报价行信息异常"),
    QUOTATION_LINEID_NULL(100055, "报价行信息异常 %s"),
    QUERY_DATA_ERR(100056, "数据查询异常"),
    PAY_DATA_ERR(100057, "支付凭证必传"),
    PAY_SEND_ERR(100058, "订单未支付取消任务发送失败"),
    PAY_END_ERR(100059, "支付截至时间必传"),
    STATUS_ERR(100061, "支付状态异常"),
    PAY_STATUS_ERR(100060, "订单状态或者支付方式不支持当前操作"),
    INQ_NOT_NULL(100063, "需求单信息不存在"),
    DISCOUNT_CHECK_ERR(100062, "行折扣金额和头折扣金额不等于总折扣金额"),
    AMOUNT_ERR(100064, "实际总金额与传入金额不相等"),
    SUPPLIER_ERR(100065, "供应商编号不正确或者类型不正确，请确认后重新填写 %s"),
    SUPPLIER_PARAM_ERR(100066, "供应商信息和进价信息必填"),
    REPLACE_SUPPLIER_DATA_ERR(100067, "此sku做过指定供应商处理，不能发起赋码申请 %s"),
    MDM_LINE_SKU_ERR(100068, "此sku做了赋码申请处理，不能发起指定供应商申请 %s"),
    SKU_AFTER_SALES_ERROR(10050,"此物料不支持部分售后，SKU号：%s"),
    WORKNO_ERR(100069, "工单信息不存在"),
    PROCESSING_ERR(100070, "订单取消异常,此订单有流程在正在审批中!"),
    REQUEST_CANCEL_ERR(100071, "订单取消异常,订单已不支持取消操作!"),
    ORDER_CANCEl_EXISTED_ERROR(100072, "该订单已存在修改申请信息!"),
    REFUND_ERROR(100073, "退款结果异常!"),
    PURCHASECODE_ERR(100069, "采购单位编号为空"),
    reportCode_ERR(100070, "报备号不存在 %s"),
    ;

    ResCodeEnum(Integer errCode, String errMsg) {
        this.errCode = errCode;
        this.errMsg = errMsg;

    }

    private Integer errCode;
    private String errMsg;

    public Integer getErrCode() {
        return errCode;
    }

    public String getErrMsg() {
        return errMsg;
    }

}
